### ISSUE TITLE
Roadmap: Finales Konzept Präsentation erstellen

### ISSUE THREAD

**Issue by BurkiWorld** [YanisDeplazes/Analyrics#4]
# Finales Konzept Präsentation erstellen

## Datum: 11.10.

Präsentation pro Gruppe:
- [x] [Projekttitel (Arbeitstitel, Fragestellung, 250-300 Wörter zur Idee, Was wollt ihr machen? Was interessiert euch daran? Wo verortet ihr das Projekt?](https://github.com/YanisDeplazes/STUWE1/issues/10)
- [x] [Inhalte, Story, Datensätze](https://github.com/YanisDeplazes/STUWE1/issues/9)
- [x] [visuelle Referenzen, Skizzen, Tests mit API](https://github.com/YanisDeplazes/STUWE1/issues/11)
- [x] [Projektarchitektur mit Diagramm](https://github.com/YanisDeplazes/STUWE1/issues/12)
- [x] [Requirementsanalyse (User Stories, FR, NFR)](https://github.com/YanisDeplazes/STUWE1/issues/13)
