### ISSUE TITLE
Roadmap: Schriftliche Dokumentation erstellen

### ISSUE THREAD

**Issue by YanisDeplazes** [YanisDeplazes/Analyrics#5]
# Schriftliche Dokumentation erstellen

## Date: 20.12

gemäss PDF Doku

- [x] [Slides der Schlusspräsentation](https://github.com/YanisDeplazes/STUWE1/issues/21)
- [x] [Testplan und -protokolle (min. 5 Unit/Component Tests, 2 End-To-End Tests)](https://github.com/YanisDeplazes/STUWE1/issues/22)
- [x] [Performanceanalyse](https://github.com/YanisDeplazes/STUWE1/issues/23)
- [x] [Screenshots und Videos](https://github.com/YanisDeplazes/STUWE1/issues/24)
- [x] [Code als Zip](https://github.com/YanisDeplazes/STUWE1/issues/25)
