### ISSUE TITLE
Roadmap: Finales Konzept Abgabe finalisieren

### ISSUE THREAD

**Issue by BurkiWorld** [YanisDeplazes/Analyrics#6]
# Finales Konzept Abgabe finalisieren

## Datum: 15.10.

- [x] [Finales Konzept (mit Feedback aus der Präsentation)](https://github.com/YanisDeplazes/STUWE1/issues/14)
- [x] [Projektarchitektur mit Diagramm](https://github.com/YanisDeplazes/STUWE1/issues/15)
- [x] [Requirementsanalyse (User Stories, FR, NFR)](https://github.com/YanisDeplazes/STUWE1/issues/16)
