### ISSUE TITLE
Roadmap: Projektstand Abgabe finalisieren

### ISSUE THREAD

**Issue by YanisDeplazes** [YanisDeplazes/Analyrics#8]
#  Projektstand Abgabe finalisieren

## Date: 19.11

- [x] [Wöchentlicher Snapshot vom Projektboard](https://github.com/YanisDeplazes/STUWE1/issues/17)
- [x] [Pro Person aus Fokus I zwei Code Reviews (Link auf Pull Request)](https://github.com/YanisDeplazes/STUWE1/issues/18)
- [x] [Zwischenstand des Codes](https://github.com/YanisDeplazes/STUWE1/issues/19)
